#!/usr/bin/env bash
# Usage: ./1-world_wide_web <domain> <subdomain>
# Display information about subdomains.

domain_information () {
    local subdomain="$2"
    local domain="$1"
    local ip_address=$(dig +short "$subdomain"."$domain" | tail -n1)
    local record_type=$(dig +short -t "$subdomain" "$domain" | awk '{print $1}')
    echo "The subdomain $subdomain is a $record_type record and points to $ip_address"
}

if [ "$#" == 1 ]
then
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" == 2 ]
then
  domain_information "$1" "$2"
fi
