#!/usr/bin/env bash
# This script configures Nginx on a new Ubuntu machine
# to include a custom HTTP response header - X-Served-By

# Install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configure custom header in Nginx
echo "add_header X-Served-By \$HOSTNAME;" | sudo tee -a /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart
