#!/usr/bin/env bash
# This script installs and configures HAproxy on a new Ubuntu machine
# to distribute traffic using a roundrobin algorithm to web-01 and web-02

# Install HAproxy
sudo apt-get update
sudo apt-get -y install haproxy

# Configure HAproxy
echo "frontend lb-frontend
    bind *:80
    mode http
    default_backend lb-backend

backend lb-backend
    mode http
    balance roundrobin
    option http-server-close
    server web-01 488804-web-01:80 check
    server web-02 488804-web-02:80 check" | sudo tee -a /etc/haproxy/haproxy.cfg

# Restart HAproxy to apply changes
sudo service haproxy restart
