#!/usr/bin/env bash
# This short script fixes the issue with Nginx not listening on port 80

sed -i 's/listen 80 default_server;/listen 80;/g' /etc/nginx/sites-available/default
service nginx restart
